<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Title</title>
  <link rel="stylesheet" href="/App/css/common.css">
  <script src="/App/util/common.js"></script>
  <script src="/App/libs/jquery/jquery/jquery-1.8.3.min.js"></script>
  <!--注意引入公共css 和 js 要以 view 下面的页面为基准 根目录是项目名称-->
</head>
<body>